import Head from "next/head";
import PageContent from "~/components/PageContent";
import Link from "next/link";
import { Button } from "@nextui-org/react";

type GetStartedProps = {
  onSubmit: () => void;
};

export default function GetStarted({ onSubmit }: GetStartedProps) {
  return (
    <>
      <Head>
        <title>Test app!</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageContent>
        <div className="flex flex-col gap-4">
          <h1 className="text-2xl text-gray-900">
            Let's see what you may be eligible for
          </h1>
          <div>
            This tool helps you see what home electrification incentives you may
            qualify for.
          </div>
          <Button color="primary" onPress={onSubmit}>
            Get Started
          </Button>
        </div>
      </PageContent>
    </>
  );
}
