import Head from "next/head";
import { Button } from "@nextui-org/react";
import Link from 'next/link';
import PageContent from "~/components/PageContent";

export default function Home() {
  return (
    <>
      <Head>
        <title>Test app!</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageContent>
        <div className="flex flex-col gap-4">
        <h1 className="text-2xl text-gray-900">Let's see what you may be eligible for</h1>
          <div>
            This tool helps you see what home electrification incentives you may qualify for.
          </div>
          <Link href="/basic-info">
            <Button color="primary">Get Started</Button>
          </Link>
        </div>
      </PageContent>
    </>
  );
}
